name: Build CRT contribution SVGs

on:
  workflow_dispatch:
  schedule:
    - cron: '15 10 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Generate SVGs
        uses: stefashkaa/github-profile-crt@v1
        with:
          output-dir: assets
          themes: ice,neon,crt
          github-user: Optional-BhanuPrakash
